In [2]:
# ==========================================================
# TCGA Breast Cancer Biomarker Discovery
# Author: Pal Rabheru
# Project 4 - Bioinformatics Portfolio
# ==========================================================

# Import required libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Display plots inside the notebook
%matplotlib inline

# Better looking plots
plt.style.use("ggplot")

print("Libraries imported successfully!")

Libraries imported successfully!

In [3]:
expression = pd.read_csv(
    "../data/raw/TCGA-BRCA.star_fpkm.tsv.gz",
    sep="\t",
    compression="gzip"
)

In [4]:
expression.head()

,Ensembl_ID,TCGA-D8-A146-01A,TCGA-AQ-A0Y5-01A,TCGA-C8-A274-01A,TCGA-BH-A0BD-01A,TCGA-B6-A1KC-01B,TCGA-AC-A62V-01A,TCGA-AO-A0J5-01A,TCGA-BH-A0B1-01A,TCGA-A2-A0YM-01A,...,TCGA-E2-A1IG-01A,TCGA-E9-A1NA-01A,TCGA-D8-A1JP-01A,TCGA-AR-A252-01A,TCGA-D8-A1XL-01A,TCGA-BH-A0EI-01A,TCGA-E2-A1IO-01A,TCGA-E2-A15R-01A,TCGA-B6-A0IP-01A,TCGA-A1-A0SN-01A
0,ENSG00000000003.15,3.816190,2.034638,4.823000,3.028003,2.865503,2.122341,2.805272,4.146924,4.286985,...,3.061880,2.407924,3.271246,3.250310,3.677587,4.426251,4.245123,1.234747,5.072925,1.956800
1,ENSG00000000005.6,1.796473,0.134221,0.000000,1.058801,0.166972,0.275722,0.428571,0.113300,0.129217,...,0.037453,0.042924,0.023326,1.961364,0.000000,0.101516,0.229219,0.136716,0.172488,0.015212
2,ENSG00000000419.13,4.971102,5.159173,5.107052,4.595068,4.693615,5.189662,3.824147,5.073178,4.827900,...,4.533395,4.531319,5.222078,4.425009,5.722215,5.189046,4.907208,5.077508,4.634012,6.164261
3,ENSG00000000457.14,2.656428,2.324868,3.407869,2.659925,2.249506,1.033723,2.664597,2.316320,1.677350,...,2.238512,2.089295,3.258172,2.244644,2.216982,1.995340,2.328664,2.986848,2.738357,2.391108
4,ENSG00000000460.17,1.395556,1.088888,2.505002,2.473917,1.458435,1.148739,1.141171,1.784420,2.243730,...,1.210015,1.184407,2.191405,1.322620,1.754845,1.500853,1.140451,2.033934,1.839194,1.681719

In [5]:
expression.shape

(60660, 1227)

In [6]:
expression.info()

<class 'pandas.DataFrame'>
RangeIndex: 60660 entries, 0 to 60659
Columns: 1227 entries, Ensembl_ID to TCGA-A1-A0SN-01A
dtypes: float64(1226), str(1)
memory usage: 567.9 MB

In [7]:
expression_original = expression.copy()

In [8]:
expression["Ensembl_ID"] = (
    expression["Ensembl_ID"]
    .str.split(".")
    .str[0]
)

In [9]:
expression.head()

,Ensembl_ID,TCGA-D8-A146-01A,TCGA-AQ-A0Y5-01A,TCGA-C8-A274-01A,TCGA-BH-A0BD-01A,TCGA-B6-A1KC-01B,TCGA-AC-A62V-01A,TCGA-AO-A0J5-01A,TCGA-BH-A0B1-01A,TCGA-A2-A0YM-01A,...,TCGA-E2-A1IG-01A,TCGA-E9-A1NA-01A,TCGA-D8-A1JP-01A,TCGA-AR-A252-01A,TCGA-D8-A1XL-01A,TCGA-BH-A0EI-01A,TCGA-E2-A1IO-01A,TCGA-E2-A15R-01A,TCGA-B6-A0IP-01A,TCGA-A1-A0SN-01A
0,ENSG00000000003,3.816190,2.034638,4.823000,3.028003,2.865503,2.122341,2.805272,4.146924,4.286985,...,3.061880,2.407924,3.271246,3.250310,3.677587,4.426251,4.245123,1.234747,5.072925,1.956800
1,ENSG00000000005,1.796473,0.134221,0.000000,1.058801,0.166972,0.275722,0.428571,0.113300,0.129217,...,0.037453,0.042924,0.023326,1.961364,0.000000,0.101516,0.229219,0.136716,0.172488,0.015212
2,ENSG00000000419,4.971102,5.159173,5.107052,4.595068,4.693615,5.189662,3.824147,5.073178,4.827900,...,4.533395,4.531319,5.222078,4.425009,5.722215,5.189046,4.907208,5.077508,4.634012,6.164261
3,ENSG00000000457,2.656428,2.324868,3.407869,2.659925,2.249506,1.033723,2.664597,2.316320,1.677350,...,2.238512,2.089295,3.258172,2.244644,2.216982,1.995340,2.328664,2.986848,2.738357,2.391108
4,ENSG00000000460,1.395556,1.088888,2.505002,2.473917,1.458435,1.148739,1.141171,1.784420,2.243730,...,1.210015,1.184407,2.191405,1.322620,1.754845,1.500853,1.140451,2.033934,1.839194,1.681719

In [10]:
expression.isnull().sum().sum()

np.int64(0)

In [11]:
expression["Ensembl_ID"].duplicated().sum()

np.int64(44)

In [12]:
duplicates = expression[
    expression["Ensembl_ID"].duplicated(keep=False)
]

duplicates.head(20)

,Ensembl_ID,TCGA-D8-A146-01A,TCGA-AQ-A0Y5-01A,TCGA-C8-A274-01A,TCGA-BH-A0BD-01A,TCGA-B6-A1KC-01B,TCGA-AC-A62V-01A,TCGA-AO-A0J5-01A,TCGA-BH-A0B1-01A,TCGA-A2-A0YM-01A,...,TCGA-E2-A1IG-01A,TCGA-E9-A1NA-01A,TCGA-D8-A1JP-01A,TCGA-AR-A252-01A,TCGA-D8-A1XL-01A,TCGA-BH-A0EI-01A,TCGA-E2-A1IO-01A,TCGA-E2-A15R-01A,TCGA-B6-A0IP-01A,TCGA-A1-A0SN-01A
23,ENSG00000002586,5.750030,5.535789,4.503978,4.986789,3.334740,6.461786,5.721693,5.014721,4.687212,...,5.887506,5.872238,5.616243,4.548788,4.093231,5.620959,5.579835,3.990265,4.830098,5.439630
24,ENSG00000002586,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
5507,ENSG00000124333,4.454426,4.660415,4.740944,4.577755,5.030438,4.627893,4.625569,5.101415,4.397324,...,4.515958,4.105670,5.784247,5.323035,4.277300,4.630662,4.145188,4.002306,4.693336,4.920217
5508,ENSG00000124333,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
5509,ENSG00000124334,0.058940,0.063089,0.107956,0.413377,0.023894,0.011209,0.130272,0.039138,0.126973,...,0.118094,0.307429,0.229711,0.083656,0.308128,0.030689,0.240375,0.027862,0.244035,0.510152
5510,ENSG00000124334,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
12082,ENSG00000167393,1.249870,0.693052,1.191436,0.970927,1.217107,3.064917,1.307079,0.763242,0.971810,...,1.315624,1.188338,1.267236,0.575796,1.502280,1.097948,1.109962,1.519592,1.292546,1.120485
12083,ENSG00000167393,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
12508,ENSG00000169084,3.200834,3.120369,3.386852,3.211168,2.740712,3.652314,3.223994,2.822710,1.836005,...,3.270529,3.711275,3.154178,2.520774,3.293679,2.319242,2.428839,3.040927,3.086546,3.200457
12509,ENSG00000169084,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
12512,ENSG00000169093,3.055664,3.074848,2.577272,2.992188,2.868509,4.816774,3.300226,2.681742,1.458487,...,3.426761,2.984152,2.733376,2.744269,3.575687,3.887623,2.846914,3.117230,3.402449,3.581628
12513,ENSG00000169093,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
12514,ENSG00000169100,7.663113,7.485312,8.092967,7.706849,7.254805,9.574839,7.784547,7.073189,6.580482,...,7.694962,8.514183,7.371827,6.934342,8.753496,7.583709,7.837151,7.928210,8.269377,8.464593
12515,ENSG00000169100,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
14511,ENSG00000178605,3.768650,3.478040,3.487486,3.645367,2.968238,5.819957,4.101465,2.927934,2.616099,...,3.927451,4.085510,2.799564,2.677463,4.753364,2.883582,3.612352,3.580929,4.506189,4.304847
14512,ENSG00000178605,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
15173,ENSG00000182162,1.307137,0.562181,0.521654,1.404794,0.872474,1.163563,1.076080,0.915865,0.834873,...,0.646900,1.065917,1.262974,3.511949,1.751121,0.584193,1.927252,0.413811,1.269811,1.695370
15174,ENSG00000182162,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
15232,ENSG00000182378,1.650121,1.283092,1.772350,1.541019,0.969381,3.340163,1.758602,1.437015,1.464825,...,1.294430,1.946207,2.238023,1.708540,2.499297,0.932137,1.488206,1.480524,2.179352,2.121148
15233,ENSG00000182378,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [13]:
expression = expression.drop_duplicates(
    subset="Ensembl_ID",
    keep="first"
)

In [14]:
expression["Ensembl_ID"].duplicated().sum()

np.int64(0)

In [15]:
expression.shape

(60616, 1227)